name: Deploy static content to Pages

env:
  ROOT_DIR: wwwroot
  PUBLISH_DIR: bin/Release/net9.0/publish/wwwroot

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.ROOT_DIR }}/index.html
          base_href: /SlimeIMWiki/

      - name: Clone file
        run: cp "${{ env.ROOT_DIR }}/index.html" "${{ env.ROOT_DIR }}/404.html"

      - name: Update Product Token
        run: |
          sed -i 's|"ProductToken": ""|"ProductToken": "${{ secrets.BLAZORISE_PRODUCT_TOKEN }}"|g' "${{ env.ROOT_DIR }}/appsettings.json"

      - name: Get latest .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"

      - name: Publish app
        run: dotnet workload restore && dotnet publish -c Release

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
